export const SET_STORY_DETAILS= 'SET_STORY_DETAILS';
export const SET_MINI_PROFILE_DETAILS = 'SET_MINI_PROFILE_DETAILS';
export const SET_SIDE_POST_DETAILS = 'SET_SIDE_POST_DETAILS';

export const TOGGLE_SIDE_FRAME = 'TOGGLE_SIDE_FRAME';
export const TOGGLE_MESSAGE_FRAME = 'TOGGLE_MESSAGE_FRAME';